### PR TITLE
Using chakra UI prepare react frontend

### PR DESCRIPTION
**Pull request by Sarthak-16XO**

### CODE REVIEW

**Comment by panditamey** [comment]
iframe.js:300 Info: The current domain is not authorized for OAuth operations. This will prevent signInWithPopup, signInWithRedirect, linkWithPopup and linkWithRedirect from working. Add your domain (chatgpt-using-gptneo.netlify.app) to the OAuth redirect domains list in the Firebase console -> Authentication -> Settings -> Authorized domains tab.


Also add .vscode in .gitignore

**Comment by Sarthak-16XO** [comment]
> 

Done

**Comment by panditamey** [comment]
Good Work !

**Comment by gdgc-ace** [comment]
Hey Just give what envs to set ?

**Pull request merged**
